#{{AUTOGENERATED_SCRIPT}}#

#{{SDC_AUTOGENERATED_VARS}}#

proc print_violations_summary {severities} {
    foreach severity $severities {
        puts "$severity : [get_violation_info -severity $severity]"
    }
}

proc fail_violation {severity} {
    set count [get_violation_info -severity $severity]
    if {$count} {
        error "Error: count:$count  severity:$severity"
    }
}

proc fail_violations {{severities "warning error fatal"}} {
    foreach severity $severities {
        fail_violation $severity
    }
}

## Determine the number of CPU cores to use for dispatched jobs
## Place an upper limit at 16 to avoid using too many licences at once
proc get_dispatch_value {} {
    set cores 1
    if {![catch {open "/proc/cpuinfo"} f]} {
        set cores [regexp -all -line {^processor\s} [read $f]]
        close $f
        if {$cores > 0} {
            if {$cores > 16} {
                return 16
            }
        }
    }
    return $cores
}

set_app_var enable_rdc true

# Include additional config files
set config_list [split $config_files " "]
foreach config $config_list {
    source -e $config
}

set search_path $include_dirs

if {$enable_liberty} {
    set link_library $link_library
} else {
    waive_violation -app setup -add global_waiver_1 -filter { Tag==COM_OPT010 } -comment {Search path is not needed in pure RTL lint}
}

analyze -format sverilog -vcs "$sources -sverilog $vcs_opts"
elaborate $top_module

read_sdc $sdc_file

# Include additional config files
set config_list [split $pre_check_config_files " "]
foreach config $config_list {
    source -e $config
}


# Check RDC
set nb_cores [eval get_dispatch_value]
check_rdc -j ${nb_cores}

# Include waiver file
set waiver_list [split $waiver_files " "]
foreach waiver $waiver_list {
    source $waiver
}

report_rdc -verbose -file $report_file
save_session -session rdc_session -compression zstd
print_violations_summary $all_severities
fail_violations $failing_severities
