#{{AUTOGENERATED_SCRIPT}}#

#{{SDC_AUTOGENERATED_VARS}}#

proc print_violations_summary {severities} {
    foreach severity $severities {
        puts "$severity : [get_violation_info -severity $severity]"
    }
}

proc fail_violation {severity} {
    set count [get_violation_info -severity $severity]
    if {$count} {
        error "Error: count:$count  severity:$severity"
    }
}

proc fail_violations {{severities "warning error fatal"}} {
    foreach severity $severities {
        fail_violation $severity
    }
}

set_app_var enable_rdc true

# Include additional config files
set config_list [split $config_files " "]
foreach config $config_list {
    source $config
}

# Include waiver file
set waiver_list [split $waiver_files " "]
foreach waiver $waiver_list {
    source $waiver
}

set search_path $include_dirs

if {$enable_liberty} {
    set link_library $link_library
} else {
    waive_violation -app setup -add global_waiver_1 -filter { Tag==COM_OPT010 } -comment {Search path is not needed in pure RTL lint}
}

analyze -format sverilog -vcs "$sources -sverilog $vcs_opts"
elaborate $top_module

read_sdc $sdc_file

# Check RDC
check_rdc
report_rdc -verbose -file $report_file
print_violations_summary $all_severities
fail_violations $failing_severities
